app/snip/models.py
from app import db
from app.snip import constants as SNIP


class Snippet(db.Model):
    __tablename__ = 'Snippet'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    type = db.Column(db.String(50))
    code = db.Column(db.String(500))

    def __init__(self, name=None, type=None, code=None):
        self.name = name
        self.type = type
        self.code = code

    def getCode(self):
        return self.code

    def __repr__(self):
        return '<User %r>' % (self.name)

app/users/models.py
from app import db
from app.users import constants as USER


class User(db.Model):

    __tablename__ = 'users_user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(20))
    role = db.Column(db.SmallInteger, default=USER.USER)
    status = db.Column(db.SmallInteger, default=USER.NEW)

    def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

    def getStatus(self):
        return USER.STATUS[self.status]

    def getRole(self):
        return USER.ROLE[self.role]

    def __repr__(self):
        return '<User %r>' % (self.name)

app/snip/forms.py
from flask.ext.wtf import Form, TextField, TextAreaField, PasswordField, BooleanField, RecaptchaField, SelectField
from flask.ext.wtf import Required, Email, EqualTo


class snipForm(Form):
    name = TextField('Name', [Required()])
    code = TextAreaField('Code', [Required()])


class TransactionForm(Form):
    name = TextField('NickName', [Required()])
    frequency = SelectField('Frequency', choices=[("Monthy", "Monthly"), ("weekly", "weekly"), ("annual", "annual")])

app/users/forms.py
from flask.ext.wtf import Form, TextField, PasswordField, BooleanField, RecaptchaField
from flask.ext.wtf import Required, Email, EqualTo


class LoginForm(Form):
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])


class RegisterForm(Form):
    name = TextField('NickName', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField('Repeat Password', [
        Required(),
        EqualTo('confirm', message='Passwords must match')
    ])
    accept_tos = BooleanField('I accept the TOS', [Required()])
    recaptcha = RecaptchaField()

app/__init__.py
from flask import Flask, render_template
from flask.ext.sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.users.views import mod as usersModule
app.register_blueprint(usersModule)
from app.snip.views import mod as snippetModule
app.register_blueprint(snippetModule)

# Later on you'll import the other blueprints the same way:
#from app.comments.views import mod as commentsModule
#from app.posts.views import mod as postsModule
#app.register_blueprint(commentsModule)
#app.register_blueprint(postsModule

app/snip/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash
from app import db
from app.snip.models import Snippet
from app.snip.forms import snipForm
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter
from pygments.styles import get_style_by_name


mod = Blueprint('account', __name__, url_prefix='/snippets')


@mod.route('/add/', methods=['GET', 'POST'])
def login():
    form = snipForm(request.form)

    if form.validate_on_submit():
        snip = Snippet(form.name.data, "html", form.code.data)
        db.session.add(snip)
        db.session.commit()
        flash('Snipeet added', 'success-message')
    return render_template("snip/addSnip.html", form=form)


@mod.route('/view/', methods=['GET', 'POST'])
def view():
    snippet = Snippet.query.filter_by(id=2).first()
    code =  highlight(snippet.code, PythonLexer(), HtmlFormatter())
    return render_template("snip/Snip.html", snippet=snippet, code=code)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash
from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('/me/')
@requires_login
def home():
    return render_template("users/profile.html", user=g.user)


@mod.before_request
def before_request():
    """
    pull user's profile from the database before every request are treated
    """
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['user_id'] = user.id
            flash('Welcome %s' % user.name)
            return redirect(url_for('users.home'))
        flash('Wrong email or password', 'error-message')
    return render_template("users/login.html", form=form)


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        user = User(form.name.data, form.email.data, \
        generate_password_hash(form.password.data))
        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()

        # Log the user in, as he now has an id
        session['user_id'] = user.id

        # flash will display a message to the user
        flash('Thanks for registering')
        # redirect user to the 'home' method of the user module.
        return redirect(url_for('users.home'))
    return render_template("users/register.html", form=form)

app/templates/base.html
 <html>
    <head>
      <title>{% block title %}My Site{% endblock %}</title>
      {% block css %}
        <link rel="stylesheet" href="/static/css/bootstrap.css" />
        <link rel="stylesheet" href="/static/css/monokai.css" />
      {% endblock %}
      {% block script %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="/static/js/tabby.js" ></script>
         <script src="/static/js/highlight.js" ></script>
        <script>
          $(document).ready(function(){
              $(".tabby").tabby();
          });
        </script>
      {% endblock %}
    </head>
    <body>

    TODO : -https://github.com/ajaxorg/ace
      <div id="header">{% block header %}{% endblock %}</div>
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
            <p class="message flash-{{ category }}">{{ msg }}</p>
          {% endfor %}
        </div>
      </div>
      <div id="content">{% block content %}{% endblock%}</div>
      <div id="footer">{% block footer %}{% endblock%}</div>
    </body>
  </html>

app/templates/forms/macros.html
  {% macro render_field(field) %}
      <div class="form_field">
      {{ field.label(class="label") }}
      {% if field.errors %}
          {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
          {{ field(class=css_class, **kwargs) }}
          <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
      {% else %}
          {{ field(**kwargs) }}
      {% endif %}
      </div>
  {% endmacro %}

app/templates/snip/Snip.html
<style>
.highlight .hll { background-color: #49483e }
.highlight  { background: #272822; color: #f8f8f2 }
.highlight .c { color: #75715e } /* Comment */
.highlight .err { color: #960050; background-color: #1e0010 } /* Error */
.highlight .k { color: #66d9ef } /* Keyword */
.highlight .l { color: #ae81ff } /* Literal */
.highlight .n { color: #f8f8f2 } /* Name */
.highlight .o { color: #f92672 } /* Operator */
.highlight .p { color: #f8f8f2 } /* Punctuation */
.highlight .cm { color: #75715e } /* Comment.Multiline */
.highlight .cp { color: #75715e } /* Comment.Preproc */
.highlight .c1 { color: #75715e } /* Comment.Single */
.highlight .cs { color: #75715e } /* Comment.Special */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .kc { color: #66d9ef } /* Keyword.Constant */
.highlight .kd { color: #66d9ef } /* Keyword.Declaration */
.highlight .kn { color: #f92672 } /* Keyword.Namespace */
.highlight .kp { color: #66d9ef } /* Keyword.Pseudo */
.highlight .kr { color: #66d9ef } /* Keyword.Reserved */
.highlight .kt { color: #66d9ef } /* Keyword.Type */
.highlight .ld { color: #e6db74 } /* Literal.Date */
.highlight .m { color: #ae81ff } /* Literal.Number */
.highlight .s { color: #e6db74 } /* Literal.String */
.highlight .na { color: #a6e22e } /* Name.Attribute */
.highlight .nb { color: #f8f8f2 } /* Name.Builtin */
.highlight .nc { color: #a6e22e } /* Name.Class */
.highlight .no { color: #66d9ef } /* Name.Constant */
.highlight .nd { color: #a6e22e } /* Name.Decorator */
.highlight .ni { color: #f8f8f2 } /* Name.Entity */
.highlight .ne { color: #a6e22e } /* Name.Exception */
.highlight .nf { color: #a6e22e } /* Name.Function */
.highlight .nl { color: #f8f8f2 } /* Name.Label */
.highlight .nn { color: #f8f8f2 } /* Name.Namespace */
.highlight .nx { color: #a6e22e } /* Name.Other */
.highlight .py { color: #f8f8f2 } /* Name.Property */
.highlight .nt { color: #f92672 } /* Name.Tag */
.highlight .nv { color: #f8f8f2 } /* Name.Variable */
.highlight .ow { color: #f92672 } /* Operator.Word */
.highlight .w { color: #f8f8f2 } /* Text.Whitespace */
.highlight .mf { color: #ae81ff } /* Literal.Number.Float */
.highlight .mh { color: #ae81ff } /* Literal.Number.Hex */
.highlight .mi { color: #ae81ff } /* Literal.Number.Integer */
.highlight .mo { color: #ae81ff } /* Literal.Number.Oct */
.highlight .sb { color: #e6db74 } /* Literal.String.Backtick */
.highlight .sc { color: #e6db74 } /* Literal.String.Char */
.highlight .sd { color: #e6db74 } /* Literal.String.Doc */
.highlight .s2 { color: #e6db74 } /* Literal.String.Double */
.highlight .se { color: #ae81ff } /* Literal.String.Escape */
.highlight .sh { color: #e6db74 } /* Literal.String.Heredoc */
.highlight .si { color: #e6db74 } /* Literal.String.Interpol */
.highlight .sx { color: #e6db74 } /* Literal.String.Other */
.highlight .sr { color: #e6db74 } /* Literal.String.Regex */
.highlight .s1 { color: #e6db74 } /* Literal.String.Single */
.highlight .ss { color: #e6db74 } /* Literal.String.Symbol */
.highlight .bp { color: #f8f8f2 } /* Name.Builtin.Pseudo */
.highlight .vc { color: #f8f8f2 } /* Name.Variable.Class */
.highlight .vg { color: #f8f8f2 } /* Name.Variable.Global */
.highlight .vi { color: #f8f8f2 } /* Name.Variable.Instance */
.highlight .il { color: #ae81ff } /* Literal.Number.Integer.Long */
</style>


hello world
{{ code|safe }}

app/templates/snip/addSnip.html
{% extends "base.html" %}
{% block content %}
	<script>var myCodeMirror = CodeMirror(document.body);</script>
	{% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="well">
      	{{ form.csrf_token }}
      	{{ render_field(form.name, class="input text") }}
      	{{ render_field(form.code, class="input text html tabby", cols="200", rows="20") }}
      	<input type="submit" value="go" class="button green">
    </form>
{% endblock %}

app/templates/users/login.html
 {% extends "base.html" %}
  {% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      <input type="submit" value="Login" class="button green">
    </form>
    <a href="{{ url_for('users.register') }}">Register</a>
  {% endblock %}

app/templates/users/register.html
 {% extends "base.html" %}
  {% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, class="input text") }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      {{ render_field(form.confirm, class="input text") }}
      {{ render_field(form.accept_tos, class="input checkbox") }}
      <label>ReCaptcha</label>
      {{ form.recaptcha }}
      <input type="submit" value="Register" class="button green">
    </form>
    <a href="{{ url_for('users.login') }}">Login</a>
  {% endblock %}